#!/bin/bash
# Quick script to check payout addresses on blockchain explorers

echo "=============================================================================="
echo "BLOCKCHAIN VERIFICATION - Scam Pool Investigation"
echo "=============================================================================="
echo ""
echo "Checking if pool payout addresses have received block rewards..."
echo ""

echo "LuckyMonster Payout Address:"
echo "  Address: 1CS1Zq3mcU4vgEonNxS6R3WfHHB4tTt3sx"
echo "  Check at: https://blockchair.com/bitcoin/address/1CS1Zq3mcU4vgEonNxS6R3WfHHB4tTt3sx"
echo "  Check at: https://mempool.space/address/1CS1Zq3mcU4vgEonNxS6R3WfHHB4tTt3sx"
echo ""

echo "zsolo.bid Payout Address:"
echo "  Address: 1Kru6EgGtM6FVYU8V1QTH2Kek7gESakBQY"
echo "  Check at: https://blockchair.com/bitcoin/address/1Kru6EgGtM6FVYU8V1QTH2Kek7gESakBQY"
echo "  Check at: https://mempool.space/address/1Kru6EgGtM6FVYU8V1QTH2Kek7gESakBQY"
echo ""

echo "=============================================================================="
echo "WHAT TO LOOK FOR:"
echo "=============================================================================="
echo ""
echo "1. COINBASE TRANSACTIONS (Block Rewards)"
echo "   - These are transactions with 3.125+ BTC"
echo "   - They come from 'Coinbase' (not an exchange, the mining reward)"
echo "   - If present: PROOF the pool found blocks"
echo ""
echo "2. TRANSACTION HISTORY"
echo "   - When did they start receiving funds?"
echo "   - How many blocks have they found?"
echo "   - Are there any outgoing transactions to miners?"
echo ""
echo "3. TOTAL RECEIVED"
echo "   - Sum of all coinbase transactions = total stolen from miners"
echo ""
echo "=============================================================================="
echo "SMOKING GUN:"
echo "=============================================================================="
echo ""
echo "If these addresses have received coinbase transactions (block rewards),"
echo "it proves the pools found blocks and kept the rewards instead of paying"
echo "miners. This is IRREFUTABLE PROOF of scam operation."
echo ""
echo "Open the URLs above in your browser to check the blockchain evidence."
echo ""
